version: '2'
services:
    boardgames-app:
        image: boardgames
        external_links:
            - boardgames-mysql:mysql
            - boardgames-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boardgames?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    boardgames-mysql:
        extends:
            file: mysql.yml
            service: boardgames-mysql
    boardgames-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: boardgames-elasticsearch
